name: Workflow
on: [push]

jobs:
  buildAndTest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: nanasess/setup-php@master
      - name: Install dependencies
        run: composer install
      - name: Install Faker
        run: composer require fzaninotto/Faker
      - name: Run chromedriver
        run: nohup $CHROMEWEBDRIVER/chromedriver --url-base=/wd/hub /dev/null 2>&1 &
      - name: Run test cases
        run: php vendor/bin/codecept run --steps -vvv --xml
